### PR TITLE
Changed regex to capture focus content as well.

### PR DESCRIPTION
**Pull request by theerfan**
Since [As far as I've gathered] the api is the same for both focus and meditate content on headspace, the only changed needed was in the url regex.
Adding that to make this repo more powerful.

### CODE REVIEW

**Comment by theerfan** [comment]
I'm just playing around with the library at this point, I didn't know github would add all of my future commits to this PR as well.
Closing PR to avoid any confusion.

**Comment by yashrathi-git** [comment]
Hello @theerfan , thanks for the PR but I don't see how moving to httpx instead of requests would be much helpful. I think main advantage of httpx is asynchronous requests, but that probably won't make this notably faster for most in this case. 
It would also be better to do individual PRs for specific and smaller changes as it would allow me to merge them directly.

**Comment by theerfan** [comment]
Hi. @yashrathi-git 
I apologize again. 
The PR was only meant to contain the first commit (changing the regex to contain focus packs as well).

After that, I started playing around with the library a little and didn't realize that any commits I would make to my fork of this repo would also appear here. Just to make it clear, I didn't mean to include the change from requests to httpx in the PR.

Anyhow, I think the point of my original PR (the regex part) still stands as a good thing, and if you agree with me, please make the change in a separate commit. :D

**Comment by yashrathi-git** [comment]
I have updated it thanks

**Pull request closed without merging**
